### PR TITLE
improve import sorting

### PR DESCRIPTION
**Pull request by fplgusmao**
Added support for imports that we use a lot in react app: `shared/utils/...` or `apps/ContentPages/components/...`

Also fixes classnames sorting together with styles. And removes the special case for dependencies which start with `@`, makes no sense to treat them differently from other deps.

### CODE REVIEW

**Comment by jmnsf** [comment]
> And removes the special case for dependencies which start with @, makes no sense to treat them differently from other deps.

I assume they'll be grouped together because of alphabetic sort?

<hr>

I don't get the `^spec` rule, what's that for usually?

**Comment by fplgusmao** [comment]
> I assume they'll be grouped together because of alphabetic sort?
Exactly, all of `@...` dependencies will be grouped together since they start with "@".

Previously we would format the following:

```javascript
import moment from "moment"
import { Text } from "@fullfabric/alma-mater"
import smthg from "@a-guys/repo"
```

into:

```javascript
import moment from "moment"

import smthg from "@a-guys/repo"
import { Text } from "@fullfabric/alma-mater"
```

with these changes it formats them as:

```javascript
import smthg from "@a-guys/repo"
import moment from "moment"

import { Text } from "@fullfabric/alma-mater"
```

**Comment by fplgusmao** [comment]
> I don't get the `^spec` rule, what's that for usually?

To separate "/spec/..." imports from others. E.g:

```javascript
import moment from "moment"

import { rest, server } from 'spec/helper/server'

import theFuncToUnitTest from "."
```

Although you reminded me that on the react-app monorepo we usually don't have that path, we have `'shared/spec/helper/...'`, or `'someApp/spec/...` so I can improve the regex for those cases.

do you think it doesn't make sense to separate these?

**Comment by jmnsf** [comment]
> with these changes it formats them as:

I'm very partial to keeping it as it was since grouping the @s makes it easier to find those imports (also looks nicer, but that's aesthetics :P)

> Although you reminded me that on the react-app monorepo we usually don't have that path

That was my question mainly, I'm not sure why we would need to import a file under `/spec`

**Comment by fplgusmao** [comment]
> I'm very partial to keeping it as it was since grouping the @s makes it easier to find those imports (also looks nicer, but that's aesthetics :P)

Fine by me! will rever that part

**Comment by fplgusmao** [comment]
Also, I'll change the regex to capture the spec imports

**Pull request merged**
